DROP DATABASE IF EXISTS surveys_app;

CREATE DATABASE surveys_app;
USE surveys_app;

CREATE TABLE users (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(150) UNIQUE NOT NULL,
    password VARCHAR(150) NOT NULL,
    username VARCHAR(100) UNIQUE NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    editedAt TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE surveys (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(500) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    editedAt TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE options (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    text VARCHAR(500) NOT NULL,
	id_survey INT UNSIGNED NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    editedAt TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (id_survey) REFERENCES surveys (id)
);

CREATE TABLE votes (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	id_user INT UNSIGNED NOT NULL,
    id_option INT UNSIGNED NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    editedAt TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (id_user) REFERENCES users (id),
    FOREIGN KEY (id_option) REFERENCES options (id)
);